In [9]:
# NDTA631 - Data Analysis and Visualization
import numpy as np
import os

print('Starting NDTA631 Assignment Analysis...')
print('Loading datasets...')

Starting NDTA631 Assignment Analysis...
Loading datasets...

In [10]:
# --- Load datasets with proper Windows paths ---
sent_df = pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\WB_FINDEX_FIN13BM.csv")

sent_df

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BGD,Bangladesh,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BEN,Benin,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BWA,Botswana,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BFA,Burkina Faso,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,KHM,Cambodia,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,TGO,Togo,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
511,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,UGA,Uganda,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
512,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZMB,Zambia,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
513,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZWE,Zimbabwe,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
514,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,SSA,Sub-Saharan Africa (excluding high income),WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public

In [11]:
withdrew_df = pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\WB_FINDEX_FIN13CM.csv")

withdrew_df

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BGD,Bangladesh,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BEN,Benin,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BWA,Botswana,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BFA,Burkina Faso,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,KHM,Cambodia,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,TGO,Togo,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
511,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,UGA,Uganda,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
512,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZMB,Zambia,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
513,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZWE,Zimbabwe,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
514,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,SSA,Sub-Saharan Africa (excluding high income),WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,O,Missing value,PU,Public

In [12]:
# Clean data by removing NaN values
sent_df_clean = sent_df.dropna(subset=['OBS_VALUE'])
withdrew_df_clean = withdrew_df.dropna(subset=['OBS_VALUE'])

In [13]:
sent_df_clean

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BGD,Bangladesh,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BEN,Benin,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BWA,Botswana,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BFA,Burkina Faso,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,KHM,Cambodia,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,TGO,Togo,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
511,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,UGA,Uganda,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
512,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZMB,Zambia,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
513,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZWE,Zimbabwe,WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
514,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,SSA,Sub-Saharan Africa (excluding high income),WB_FINDEX_FIN13BM,"Sent money from a mobile money account, monthly",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public

In [6]:
withdrew_df_clean

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BGD,Bangladesh,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BEN,Benin,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BWA,Botswana,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,BFA,Burkina Faso,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,KHM,Cambodia,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,TZA,Tanzania,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
510,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,TGO,Togo,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
511,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,UGA,Uganda,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
512,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZMB,Zambia,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
513,datastructure,WB.DATA360:DS_DATA360(1.2),I,A3,Triennial,ZWE,Zimbabwe,WB_FINDEX_FIN13CM,"Took out money from a mobile money account, mo...",_T,...,0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public

In [8]:


sent_df_clean.to_csv(r"C:\Users\Admin\OneDrive\Documents\sent_df_clean.csv")
withdrew_df_clean.to_csv(r"C:\Users\Admin\OneDrive\Documents\withdrews_df_clean.csv")

In [16]:
# Convert to NumPy arrays
sent_values = sent_df_clean['OBS_VALUE'].to_numpy(dtype=float)
withdrew_values = withdrew_df_clean['OBS_VALUE'].to_numpy(dtype=float)
if len(sent_values) > 1 and len(withdrew_values) > 1:

       # --- NumPy Calculations ---
    sent_mean, sent_median, sent_std = np.mean(sent_values), np.median(sent_values), np.std(sent_values)
   
    
    withdrew_mean, withdrew_median, withdrew_std = np.mean(withdrew_values), np.median(withdrew_values), np.std(withdrew_values)

In [30]:
    print(f"Sent Money   Mean: {sent_mean:.2f}, Median: {sent_median:.2f}, Std: {sent_std:.2f}")

Sent Money   Mean: 16.12, Median: 15.20, Std: 7.25

In [31]:
    print(f"Withdrew Money Mean: {withdrew_mean:.2f}, Median: {withdrew_median:.2f}, Std: {withdrew_std:.2f}")

Withdrew Money Mean: 16.13, Median: 15.50, Std: 6.60

In [33]:
# --- Reshape Arrays (2 columns) ---
if len(sent_values) % 2 != 0:
        sent_values = sent_values[:-1]  # drop last if odd
if len(withdrew_values) % 2 != 0:
        withdrew_values = withdrew_values[:-1]

sent_reshaped = sent_values.reshape(-1, 2)
withdrew_reshaped = withdrew_values.reshape(-1, 2)

In [34]:
sent_reshaped[:5]

array([[ 3.4114798 , 11.2210111 ],
       [19.78814569, 10.73053513],
       [ 3.48643169, 12.88795819],
       [ 2.39687495,  3.08939273],
       [ 8.52783193,  9.64203606]])

In [35]:
withdrew_reshaped[:5]

array([[ 5.07788953, 15.19596138],
       [17.45249856, 10.21599398],
       [ 2.9252437 , 12.07635567],
       [ 1.59066285,  2.96812008],
       [ 8.23140896, 10.80244449]])

In [39]:
# --- Element-wise Operations ---
min_len = min(len(sent_values), len(withdrew_values))
ratio = withdrew_values[:min_len] / (sent_values[:min_len] + 1e-6)

print("\nElement-wise Ratio (Withdrew / Sent) - first 10 values:")
ratio[:10]

Element-wise Ratio (Withdrew / Sent) - first 10 values:

array([1.48847079, 1.3542416 , 0.88196731, 0.95204879, 0.83903633,
       0.93702622, 0.66364004, 0.96074516, 0.96524041, 1.12034878])

In [41]:
    # --- Correlation ---
    if np.std(sent_values[:min_len]) > 0 and np.std(withdrew_values[:min_len]) > 0:
        correlation = np.corrcoef(sent_values[:min_len], withdrew_values[:min_len])[0, 1]
        print(f"\nCorrelation between Sent and Withdrew: {correlation:.2f}")
    else:
        print("\nCorrelation cannot be computed (no variation in data).")

Correlation between Sent and Withdrew: 0.55